name: Scheduled Health Check

on:
  schedule:
  - cron: "*/10 * * * *"
  
# 添加手动触发事件
  workflow_dispatch:
    inputs:
      manualReason:
        description: 'Input description'
        required: false
        default: 'default_value'

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make shell script executable
        run: chmod +x ./health-check.sh

      - name: Run Shell Script
        id: shell_script_run
        run: sh ./health-check.sh