name: Scheduled Health Check

# Controls when the action will run.
on:
# 添加手动触发事件
  workflow_dispatch:
    inputs:
      manualReason:
        description: 'Input description'
        required: false
        default: 'default_value'

  schedule:
    - cron: "30 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make shell script executable
        run: chmod +x ./health-check.sh

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh