name: service-check

on:
  schedule:
  - cron: "*/10 * * * *"
  
# 添加手动触发事件
  workflow_dispatch:
    inputs:
      manualReason:
        description: 'Input description'
        required: false
        default: '手动触发测试'

jobs:
  service-check:
    runs-on: ubuntu-latest 
    name: Check all sites
    env:
      WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}

    # 新任务挂起
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make shell script executable
        run: chmod +x ./src/servicecheck.sh

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./src/servicecheck.sh

      - name: Setup Git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'Actions@knloop.com'

      - name: Commit and push changes
        run: |
          git merge origin/main --no-commit --strategy=recursive --strategy-option=theirs --no-ff --no-commit :!logs/
          git add -A --force ./logs/
          git commit -am '[Automated] Update service status logs'
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
