name: service-check

on:
  schedule:
  - cron: "*/10 * * * *"
  
# 添加手动触发事件
  workflow_dispatch:
    inputs:
      manualReason:
        description: 'Input description'
        required: false
        default: 'default_value'

jobs:
  service-check:
    runs-on: ubuntu-latest 
    name: Check all sites
    env:
      WEBHOOK_KEY1: ${{ secrets.WECHAT_WEBHOOK_KEY }}

    # 新任务挂起
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make shell script executable
        run: chmod +x ./src/servicecheck.sh

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./src/servicecheck.sh
