name: Deploy Static Site to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  pages: write     # 必须有写权限来更新 GitHub Pages 分支
  id-token: write  # 必须有写权限来使用 OIDC 身份验证

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload entire repository root as artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4