name: Deploy Static Site to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read

    concurrency:
      group: deploy-pages
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4